name: 'Film SF'
base_url: 'https://filmsf.org'
archive:
  collection_id: 20204

hostnames:
  - filmsf.org
  - www.filmsf.org
  - '${HEROKU_APP_NAME}.filmsf.org'

redirects:
  - file: drupal.tsv
  - file: filmsf.tsv
