version: '3.2'
services:
  httpd:
    container_name: archive-httpd
    image: httpd:2.4
    env_file:
      - .env
    ports:
      # map $PORT to port 80 on the container, so we can access it via:
      # http://localhost:$PORT
      - '${PORT}:80'
    volumes:
      # these volumes mount all of the necessary files to /app in the container
      # to mirror where Heroku places them
      - ./httpd/:/app/httpd/
      - ./public/:/app/public/
    # this should mirror the web process command in Procfile, *except* that it
    # should include main.conf instead of heroku.conf
    command: |
      httpd -c 'Include /app/httpd/conf/main.conf' -D FOREGROUND
    networks:
      mock:
        aliases:
          # these allows us to test locally with:
          # `curl -H 'Host: $hostname' http://localhost:$PORT/...`
          - '${HEROKU_APP_NAME}.herokuapp.com'
          - archive.sf.gov
          - sftreasureisland.org
networks:
  mock:
    # this space intentionally left blank

