version: '3.2'
services:
  httpd:
    image: httpd:2.4
    env_file:
      - .env
    ports:
      - '${PORT}:80'
    volumes:
      - ./httpd/:/app/httpd/
      - ./public/:/app/public/
      - /app/.git
    command: httpd -c 'Include /app/httpd/conf/main.conf' -c 'Include /app/httpd/conf/main.conf' -D FOREGROUND
    networks:
      mock:
        aliases:
          # this is what allows us to test with the Host header
          - archive.sf.gov
          - sftreasureisland.org
networks:
  mock: