name: 'Department of Building Inspection'
base_url: 'https://sfdbi.org'
archive:
  collection_id: 20246

hostnames:
  - 'sfdbi.org'
  - '${HEROKU_APP_NAME}.sfdbi.org'

redirects:
  - map:
      /: 'https://sf.gov/departments/department-building-inspection'
  - file: 'drupal.tsv'
  - file: 'sfdbi.tsv'
  - file: 'pdfs.tsv'
