name: SF Elections
base_url: https://sfelections.sfgov.org

archive:
  collection_id: 21144

hostnames:
  - sfelections.sfgov.org
  - '${HEROKU_APP_NAME}.sfelections.sfgov.org'

redirects:
  - file: sfelections.tsv