name: SF Mayor London Breed
base_url: https://sfmayor.org

archive:
  collection_id: 20094

hostnames:
  - sfmayor.org
  - '${HEROKU_APP_NAME}.sfmayor.org'

redirects:
  - map:
      /: https://sf.gov/departments/office-mayor
  - file: drupal.tsv
  - file: sfmayor.tsv
