name: static assets

base_url: https://archive.sf.gov

static:
  path: public
  options:
    fallthrough: true

hostnames:
  - localhost
  - '${HEROKU_APP_NAME}.archive.sf.gov'
  - '${HEROKU_APP_NAME}.herokuapp.com'