name: 'Department of Emergency Management'
base_url: 'https://sfdem.org'
archive:
  collection_id: 20222

hostnames:
  - sfdem.org
  - www.sfdem.org
  - '${HEROKU_APP_NAME}.sfdem.org'

redirects:
  - file: drupal.tsv
  - file: sfdem.tsv
