name: 'Office of Small Business'
base_url: 'https://sfosb.org'
archive:
  collection_id: 19772

hostnames:
  - 'sfosb.org'
  - '${HEROKU_APP_NAME}.sfosb.org'

redirects:
  - file: drupal.tsv
  - file: sfosb.tsv
