name: deployment
on:
  deployment_status:
  workflow_dispatch:
    inputs:
      test_base_url:
        description: |
          The fully-qualified base URL of the app to test, e.g. "https://sfgov-archive.herokuapp.com"
        required: false
      test_subdomain:
        description: |
          The optional prefix for all hosts outside of the base URL hostname. This is necessary when
          testing on Heroku review apps, and is usually specified as "sfgov-archive-pr-XX" where "XX"
          is the pull request number.
        required: false

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: set TEST_BASE_URL from inputs.test_base_url
        if: inputs.test_base_url
        run: echo TEST_BASE_URL="${{ inputs.test_base_url }}" >> $GITHUB_ENV
      - name: set TEST_BASE_URL from deployment payload
        if: github.event.deployment_status.state == 'success' && github.event.deployment.payload.web_url
        run: echo TEST_BASE_URL="${{ github.event.deployment.payload.web_url }}" >> $GITHUB_ENV

      - name: set HEROKU_APP_NAME
        run: echo HEROKU_APP_NAME="$(scripts/get-app-name.js $TEST_BASE_URL)" >> $GITHUB_ENV

      - name: set TEST_SUBDOMAIN from inputs.test_subdomain
        if: inputs.test_subdomain
        run: echo TEST_SUBDOMAIN="${{ inputs.test_subdomain }}" >> $GITHUB_ENV
      - name: derive TEST_SUBDOMAIN from TEST_BASE_URL
        if: env.TEST_SUBDOMAIN == null
        run: |
          if [ "$HEROKU_APP_NAME" != "" ]; then
            echo TEST_SUBDOMAIN="${HEROKU_APP_NAME}." >> $GITHUB_ENV
          else
            echo "HEROKU_APP_NAME is empty; not setting TEST_SUBDOMAIN" >> /dev/stderr
          fi
      - name: conditionally set TEST_ENV=production
        if: github.event.deployment.environment == 'sfgov-archive' || github.event.deployment.production_environment
        run: echo TEST_ENV=production >> $GITHUB_ENV

      - name: add test subdomains (for pull requests only)
        if: contains(env.HEROKU_APP_NAME, '-pr-')
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          npm i -g heroku
          scripts/heroku-add-domains.js "$HEROKU_APP_NAME"

      - run: npm install
      - run: npm run test:features
