name: Deploy Node.js project to Azure Function App

on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Build
      shell: bash
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Publish Azure Function
      uses: Azure/functions-action@v1
      id: publish
      with:
        app-name: sfgov-archive-next
        package: .
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples