name: test
on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: validate configurations
        run: npm run validate
      - name: lint
        run: npm run lint
      - name: unit tests
        run: npm run test:unit
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ github.token }}
