name: test
on:
  deployment_status:

jobs:
  test:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    env:
      TEST_BASE_URL: ${{ github.event.deployment.payload.web_url }}
    steps:
      - if: env.TEST_BASE_URL == ''
        run: |
          echo "TEST_BASE_URL is empty; no tests can be run!"
          exit 1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          # cache: npm
          # cache-dependency-path: tests/package-lock.json
      - name: install and test
        run: |
          cd tests
          npm install
          npm test
