name: test
on:
  deployment_status:

jobs:
  test:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    env:
      TEST_BASE_URL: ${{ github.event.deployment.payload.web_url }}
    steps:
      - name: bail if TEST_BASE_URL is empty
        if: env.TEST_BASE_URL == ''
        run: |
          echo "TEST_BASE_URL is empty; no tests can be run!" > /dev/stderr
          exit 1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run tests
        run: scripts/test.sh
